version: "3.7"

services:

  php:
    build:
      context: ./php
    volumes:
      - ./php-quickstart/src:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DBNAME=${MARIADB_DBNAME}
    ports:
      - 80:80
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
      - ${SCHEMA_INIT_SQL}:/docker-entrypoint-initdb.d/schema.sql

    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data: